###########
# site.url, site.title

url:   'https://nbisweden.github.io/PythonCourse'

#google_analytics: 'UA-23985298-11'

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: default
  -
    scope:
      path: "vt17"
    values:
      layout: vt17



########
# more settings

encoding:     "utf-8"

markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'codehilite'

exclude:
- README.md

sass:
  sass_dir: css
  style:    expanded

# pygments: true
# highlighter: rouge

  
# enable vendor prefixes
gems:
  - octopress-autoprefixer
#  - autoprefixer-rails

safe: true
lsi: false


# https://github.com/jekyll/jekyll/issues/302
permalink: pretty
