###########
# site.url, site.title

url:   'https://nbisweden.github.io/workshop-python'

#google_analytics: 'UA-23985298-11'

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: default
  -
    scope:
      path: "vt17"
    values:
      layout: vt17
  -
    scope:
      path: "ht17"
    values:
      layout: ht17
  -
    scope:
      path: "ht18"
    values:
      layout: ht18
  -
    scope:
      path: "ht19"
    values:
      layout: ht19



########
# more settings

markdown: kramdown

exclude:
- README.md

sass:
  sass_dir: css
  style:    compressed # nested|expanded|compact|compressed

highlighter: rouge


# enable vendor prefixes
gems:
  - octopress-autoprefixer
#  - autoprefixer-rails

safe: true
lsi: false

# encoding:     "utf-8"
# #markdown_ext: "md"

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'codehilite'
